title = "My Hugo Site"
baseURL = "http://example.com/"
languageCode = "en-us"
theme = "your-theme-name"

# Additional configuration options can be added below
# enableRobotsTXT = true
# enableEmoji = true
# paginate = 10
# params = [ 
#   author = "Your Name"
#   description = "A brief description of your site."
# ]